Import SQLite 3

In [7]:
import sqlite3
from sqlite3 import Error
import pandas as pd

Create connection and table

In [2]:
def create_connection(db_file):
    """
    Create a database connection to the SQLite database specified by db_file.
    Returns the Connection object, or None if an error occurs.
    """
    try:
        conn = sqlite3.connect(db_file)
        print(f"SQLite version: {sqlite3.sqlite_version}")
        return conn
    except Error as e:
        print(f"Error connecting to database: {e}")
        return None

In [8]:
def create_table(conn, create_table_sql):
    """
    Create a table using the provided CREATE TABLE SQL statement.

    Parameters:
        conn: SQLite3 Connection object.
        create_table_sql: The SQL statement to create the table.
    """
    try:
        cursor = conn.cursor()
        cursor.execute(create_table_sql)
        print("Table created successfully.")
    except Error as e:
        print(f"Error creating table: {e}")

Main (New Database)

In [4]:
def main():
    database = "college.db"

    SQL_CREATE_STUDENTS_TABLE = """
        CREATE TABLE IF NOT EXISTS students (
            cid INTEGER PRIMARY KEY,
            sname TEXT NOT NULL,
            sid INTEGER NOT NULL,
            FOREIGN KEY (sid) REFERENCES students (sid)
        );
    """


    SQL_CREATE_COURSES_TABLE = """
        CREATE TABLE IF NOT EXISTS courses (
            cid INTEGER PRIMARY KEY,
            cname TEXT NOT NULL,
            noc INTEGER NOT NULL,
            FOREIGN KEY (cid) REFERENCES courses (cid)
        );
    """

    SQL_CREATE_ENROLLMENT_TABLE = """
        CREATE TABLE IF NOT EXISTS enrollments (
            cid INTEGER PRIMARY KEY,
            cname TEXT NOT NULL,
            sid INTEGER NOT NULL,
            scname TEXT NOT NULL,
            FOREIGN KEY (cid) REFERENCES courses (cid),
            FOREIGN KEY (sid) REFERENCES students (sid)
        );
    """

    # Create a database connection
    conn = create_connection(database)

    if conn is not None:
        # Create student table
        create_table(conn, SQL_CREATE_STUDENTS_TABLE)

        # Create course table
        create_table(conn, SQL_CREATE_COURSES_TABLE)

        # Create enrollment table
        create_table(conn, SQL_CREATE_ENROLLMENT_TABLE)
    else:
        print("Error! Cannot create the database connection.")

In [5]:
if __name__ == '__main__':
    main()

SQLite version: 3.37.2
Table created successfully.
Table created successfully.
Table created successfully.

View Table

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("college.db")

# Display projects table
df_students = pd.read_sql_query("SELECT * FROM students", conn)
display(df_students)

# Display tasks table
df_courses = pd.read_sql_query("SELECT * FROM courses", conn)
display(df_courses)

Empty DataFrame
Columns: [cid, sname, sid]
Index: []

Empty DataFrame
Columns: [cid, cname, noc]
Index: []